# Ref: default config, with minor tweaks
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
  Include:
    - 'Gemfile'
    - 'Gemfile.rack-1.x'
    - 'rack-test.gemspec'
    - 'Rakefile'
    - 'Thorfile'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

# Rationale: default approach forces us to indent multiline `foo = if bar` statements in an unreasonable way.
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

inherit_from: .rubocop_todo.yml

# Rationale: RSpec blocks are very long and not necessary bad. The gemspec is a configuration
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - rack-test.gemspec

# Rationale: allow Weirich-style blocks, but do not enforce them.
Style/BlockDelimiters:
  Enabled: false
